### ISSUE TITLE
error downloading large file

### ISSUE THREAD

**Issue by buptconnor** [Marjan-GH/Topical_poetry#1]
$ git clone https://github.com/Marjan-GH/Topical_poetry
Cloning into 'Topical_poetry'...
remote: Counting objects: 52, done.
remote: Total 52 (delta 0), reused 0 (delta 0), pack-reused 52
Unpacking objects: 100% (52/52), done.
Checking connectivity... done.
Downloading data/distance_all (384 MB)
Error downloading object: data/distance_all (8909800): Smudge error: Error downl                                                                                                                                                                                               oading data/distance_all (89098005141ed251798cce0f569ced0c5c90b266dd11799b0ed189                                                                                                                                                                                               eafc03500b): batch response: This repository is over its data quota. Purchase mo                                                                                                                                                                                               re data packs to restore access.

**Comment by shaomai00** [comment]
I met the same error too,have you solved it?

**Comment by Marjan-GH** [comment]
Please check the new readme file.
