### ISSUE TITLE
Error while compiling distance_server.cpp 

### ISSUE THREAD

**Issue by AIshutin** [Marjan-GH/Topical_poetry#2]
$ g++ -o distance_server distance_server.cpp 
(line from initial.sh that raise runtime error)
Error message:

distance_server.cpp: In function ‘void read_vectors(FILE*)’:
distance_server.cpp:139:32: warning: format ‘%lld’ expects argument of type ‘lon
g long int*’, but argument 3 has type ‘int*’ [-Wformat=]
    fscanf(f, "%lld", &num_words);
                      ~~~~~~~~~~^
distance_server.cpp:140:33: warning: format ‘%lld’ expects argument of type ‘lon
g long int*’, but argument 3 has type ‘int*’ [-Wformat=]
    fscanf(f, "%lld", &num_hidden);
                      ~~~~~~~~~~~^
/tmp/ccNzp9iT.o: In function `__static_initialization_and_destruction_0(int, int
)':
distance_server.cpp:(.text+0x19c6): relocation truncated to fit: R_X86_64_PC32 a
gainst `.bss'
distance_server.cpp:(.text+0x19d9): relocation truncated to fit: R_X86_64_PC32 a
gainst `.bss'
collect2: error: ld returned 1 exit status

**Comment by Marjan-GH** [comment]
Please check the new readme file.

**Comment by vaishnavsm** [comment]
"relocation truncated to fit: R_X86_64_PC32" still occurs due to GCC compiler issue. I'll upload a patch in a couple minutes.
